# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGY4YzE2Y2I0NDE1MzkzYWU4MWUyOTUxMDQ4MGE3YjA4MTU2OWU2NmE2MzJhOTJkNGVmZjhmMThjYzQwZGYyYTJkN2YzMDdiYjdlYWIwM2U3Y2YyMDMwNzU2NGVkODYxYzZjYzRlN2RlOTY5OWVjY2MxMzg3OTQ4NzZjMDI1ZTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
